ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'AWAITING_APPROVAL';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
